server:
  port: 9000

project:
  issuer: http://auth-server:9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: false # init data.sql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO