server:
  port: 9000

project:
  issuer: ${AUTH_SERVER_URL}
spring:
  datasource:
    url: ${AUTH_DATABASE_URL}
    username: ${AUTH_DATABASE_USERNAME}
    password: ${AUTH_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${AUTH_DATABASE_DDL}
    properties:
      hibernate:
        format_sql: ${SHOW_SQL}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO