server:
  port: 8081
  servlet:
    context-path: /auth

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: update
