server:
  port: 8080

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth:
      path: /oauth/**
      url: http://localhost:8081
    resource:
      path: /api/**
      url: http://localhost:8082/api

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
      scope: profile
    resource:
      userInfoUri: http://localhost:8081/auth/users/me

spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true