server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - RemoveResponseHeader=Cookie,Set-Cookie
        - StripPrefix=1
        - TokenRelay=
      routes:
        - id: messages
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/messages/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: auth-client
            client-secret: auth-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
        provider:
          my-provider:
            issuer-uri: http://auth-server:9000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO